---
title: "SQL"
output: html_notebook: default
---


```{r}

library(tidyverse)
library(sqldf)

```
```{r}
customer = read.csv("customer.csv", header=TRUE)
trans = read.csv("transaction.csv", header=TRUE)
trans

# tmp - to be like the slides
customer = customer %>%
  filter(id %in% c(1001, 1002, 1004))

trans = trans %>%
  filter(id %in% c(1, 2, 4, 5))

trans[3, ]$customer_id = 1002
trans[4, ]$customer_id = 1003
```
```{r}
sqldf("select * from customer")
```

```{r}
sqldf("select * from trans")
```


```{r}

sqldf("select * from trans join customer on trans.customer_id = customer.id")
 
```



```{r}
sqldf("SELECT customer_id, SUM(total) FROM trans GROUP BY customer_id")
```

```{r}
sqldf("select distinct province from customer")
```


```{r}
sqldf("SELECT yearID, AVG(salary) 
FROM Salaries 
GROUP BY yearID 
ORDER BY yearID ASC")
```
```{r}
sqldf("select * from customer where city !='Kingston'")
```

```{r}
sqldf("select * from trans where total > 100 or total < 200")
```
```{r}
sqldf("select * from customer where status in ('silver', 'bronze')")
```
```{r}
sqldf("select min(joined) from customer")
```

```{r}
sqldf("select customer_id, SUM(total) from trans")
```
```{r}
sqldf("SELECT id, name, MIN(joined) FROM customer;")
```

```{r}
sqldf("SELECT id, name, joined FROM customer WHERE joined = (SELECT MIN(joined) FROM customer)")
```

```{r}
sqldf("SELECT * from trans JOIN customer on trans.customer_id = customer.id;")

```

```{r}
sqldf("SELECT * from trans JOIN customer on trans.customer_id = customer.id WHERE customer.status='gold'")

```

```{r}
sqldf("CREATE TABLE song (
  id INTEGER,
  name STRING,
  release_date DATE,
  artist_id INTEGER,
  length REAL,
  album_id INTEGER
);
")
```

```{r}
sqldf("select * from trans")
```

